/**
 * User Roles Enum for RBAC across NightZone platform
 */
const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  CUSTOMER: 'CUSTOMER',
  ASTROLOGER: 'ASTROLOGER',
  PANDIT: 'PANDIT',
  COMPANY: 'COMPANY',
  MERCHANT: 'MERCHANT'
});

const ROLE_LIST = Object.values(ROLES);

/**
 * Role permission hierarchy and granular capability mapping
 */
const PERMISSIONS = Object.freeze({
  // Customer
  PLACE_ORDER: ['CUSTOMER', 'COMPANY'],
  VIEW_OWN_ORDERS: ['CUSTOMER', 'COMPANY', 'MERCHANT', 'ADMIN', 'SUPER_ADMIN'],
  WRITE_REVIEW: ['CUSTOMER', 'COMPANY'],

  // Merchant
  CREATE_PRODUCT: ['MERCHANT', 'ADMIN', 'SUPER_ADMIN'],
  EDIT_PRODUCT: ['MERCHANT', 'ADMIN', 'SUPER_ADMIN'],
  MANAGE_INVENTORY: ['MERCHANT', 'ADMIN', 'SUPER_ADMIN'],
  VIEW_MERCHANT_ANALYTICS: ['MERCHANT', 'ADMIN', 'SUPER_ADMIN'],

  // Company (B2B)
  REQUEST_BULK_QUOTE: ['COMPANY', 'ADMIN', 'SUPER_ADMIN'],
  DOWNLOAD_B2B_INVOICE: ['COMPANY', 'ADMIN', 'SUPER_ADMIN'],

  // Astrologer
  MANAGE_ASTROLOGER_PROFILE: ['ASTROLOGER', 'ADMIN', 'SUPER_ADMIN'],
  VIEW_ASTROLOGY_CONSULTATIONS: ['ASTROLOGER', 'ADMIN', 'SUPER_ADMIN'],

  // Pandit
  MANAGE_PANDIT_PROFILE: ['PANDIT', 'ADMIN', 'SUPER_ADMIN'],

  // Admin
  MANAGE_USERS: ['ADMIN', 'SUPER_ADMIN'],
  MANAGE_ROLES: ['ADMIN', 'SUPER_ADMIN'],
  APPROVE_MERCHANT: ['ADMIN', 'SUPER_ADMIN'],
  APPROVE_COMPANY: ['ADMIN', 'SUPER_ADMIN'],
  VIEW_ALL_ANALYTICS: ['ADMIN', 'SUPER_ADMIN'],
  MODERATE_ASTROLOGY: ['ADMIN', 'SUPER_ADMIN', 'MODERATOR']
});

module.exports = {
  ROLES,
  ROLE_LIST,
  PERMISSIONS
};
